spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orders_system
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

app:
  secrets:
    # HS256 secret, min 32 chars. Set via env var APP_SECRETS_JWT in CI/hosts
    jwt: ${APP_SECRETS_JWT}
    # BCrypt hashes only (do NOT store plaintext). Optional: leave blank to disable admin login.
    admin-username-hash: ${ADMIN_USERNAME_HASH:}
    admin-password-hash: ${ADMIN_PASSWORD_HASH:}
