package com.pt.ordersystem.ordersystem.product.models

enum class ProductOverrideFailureReason {
  PRODUCT_OVERRIDE_NOT_FOUND,
  PRODUCT_OVERRIDE_ALREADY_EXISTS,
  INVALID_PRODUCT_OVERRIDE_DATA,
  PRODUCT_NOT_FOUND,
  CUSTOMER_NOT_FOUND,
  UNAUTHORIZED_ACCESS,
  DATABASE_ERROR
}

