package com.pt.ordersystem.ordersystem.domains.order.models

import com.pt.ordersystem.ordersystem.domains.product.models.ProductDataForOrder
import java.math.BigDecimal
import java.time.LocalDateTime

data class Order(
  val id: String,
  val referenceId: Long,
  val orderSource: OrderSource,
  val managerId: String,
  val agentId: String?,
  val customerId: String?,

  val storeStreetAddress: String?,
  val storeCity: String?,
  val storePhoneNumber: String?,

  val customerName: String?,
  val customerPhone: String?,
  val customerEmail: String?,
  val customerStreetAddress: String?,
  val customerCity: String?,
  val customerStateId: String?,

  val status: OrderStatus,
  val products: List<ProductDataForOrder>,
  val productsVersion: Int,
  val totalPrice: BigDecimal,
  val discount: BigDecimal,
  val vat: BigDecimal,
  val linkExpiresAt: LocalDateTime,
  val notes: String,
  val placedAt: LocalDateTime?,
  val doneAt: LocalDateTime?,
  val createdAt: LocalDateTime,
  val updatedAt: LocalDateTime,
)

fun OrderDbEntity.toModel(): Order = Order(
  id = id,
  referenceId = referenceId,
  orderSource = OrderSource.valueOf(orderSource),
  managerId = managerId,
  agentId = agentId,
  customerId = customerId,
  storeStreetAddress = storeStreetAddress,
  storeCity = storeCity,
  storePhoneNumber = storePhoneNumber,
  customerName = customerName,
  customerPhone = customerPhone,
  customerEmail = customerEmail,
  customerStreetAddress = customerStreetAddress,
  customerCity = customerCity,
  customerStateId = customerStateId,
  status = OrderStatus.valueOf(status),
  products = products,
  productsVersion = productsVersion,
  totalPrice = totalPrice,
  discount = discount,
  vat = vat,
  linkExpiresAt = linkExpiresAt,
  notes = notes,
  placedAt = placedAt,
  doneAt = doneAt,
  createdAt = createdAt,
  updatedAt = updatedAt,
)

fun Order.toDto(): OrderDto = OrderDto(
  id = id,
  referenceId = referenceId,
  orderSource = orderSource,
  managerId = managerId,
  agentId = agentId,
  customerId = customerId,
  storeStreetAddress = storeStreetAddress,
  storeCity = storeCity,
  storePhoneNumber = storePhoneNumber,
  customerName = customerName,
  customerPhone = customerPhone,
  customerEmail = customerEmail,
  customerStreetAddress = customerStreetAddress,
  customerCity = customerCity,
  customerStateId = customerStateId,
  status = status,
  products = products,
  productsVersion = productsVersion,
  totalPrice = totalPrice,
  discount = discount,
  vat = vat,
  linkExpiresAt = linkExpiresAt,
  notes = notes,
  placedAt = placedAt,
  doneAt = doneAt,
  createdAt = createdAt,
  updatedAt = updatedAt,
)

fun Order.toPublicDto(): OrderPublicDto = OrderPublicDto(
  managerId = managerId,
  referenceId = referenceId,
  status = status,
  customerId = customerId,
)

fun Order.toEntity(): OrderDbEntity = OrderDbEntity(
  id = id,
  referenceId = referenceId,
  orderSource = orderSource.name,
  managerId = managerId,
  agentId = agentId,
  customerId = customerId,
  storeStreetAddress = storeStreetAddress,
  storeCity = storeCity,
  storePhoneNumber = storePhoneNumber,
  customerName = customerName,
  customerPhone = customerPhone,
  customerEmail = customerEmail,
  customerStreetAddress = customerStreetAddress,
  customerCity = customerCity,
  customerStateId = customerStateId,
  status = status.name,
  products = products,
  productsVersion = productsVersion,
  totalPrice = totalPrice,
  discount = discount,
  vat = vat,
  linkExpiresAt = linkExpiresAt,
  notes = notes,
  placedAt = placedAt,
  doneAt = doneAt,
  createdAt = createdAt,
  updatedAt = updatedAt,
)
